### ISSUE TITLE
ソースの変更後にプレビューが落ちてしまいます

### ISSUE THREAD

**Issue by mrsatomaru** [tmrekk121/prev-md.vim#6]
素晴らしいプラグインをありがとうございます．

PrevMdを実行後プレビューはできるのですが，ソースを編集するとプレビューが落ち，ターミナルに戻ってします．
そのターミナルには
`export PAGER="less -R"`
`glow /tmp/vBiCx1w/1.md -p `
`$ $ $ glow /tmp/vBiCx1w/2.md -p `
`/bin/sh: 3:`
`glow: not found`
`$`
と出力されてしまうのですが，何か分かることはありますでしょうか?

**Comment by ksudate** [comment]
glowのinstallが必要です。
https://github.com/charmbracelet/glow
